// Generated by FlutterFire CLI for Firebase project: capypocket.
// Re-run `flutterfire configure --project=capypocket` to update.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT66hSkvnkb97ANwErT0HUUE-tW1jUmac',
    appId: '1:1040386855221:web:babddc693f60e801e93c7c',
    messagingSenderId: '1040386855221',
    projectId: 'capypocket',
    authDomain: 'capypocket.firebaseapp.com',
    storageBucket: 'capypocket.firebasestorage.app',
    measurementId: 'G-MRMG036861',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuarPhgX--t9R1wizzXPBvcfPXF9A5iHk',
    appId: '1:1040386855221:android:3788daa228a0a162e93c7c',
    messagingSenderId: '1040386855221',
    projectId: 'capypocket',
    storageBucket: 'capypocket.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABXSe2-K5uxcBearjAI3EM15i5Mi0Lw2Q',
    appId: '1:1040386855221:ios:c4c2ce6998906b9be93c7c',
    messagingSenderId: '1040386855221',
    projectId: 'capypocket',
    storageBucket: 'capypocket.firebasestorage.app',
    iosBundleId: 'com.example.capyproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABXSe2-K5uxcBearjAI3EM15i5Mi0Lw2Q',
    appId: '1:1040386855221:ios:c4c2ce6998906b9be93c7c',
    messagingSenderId: '1040386855221',
    projectId: 'capypocket',
    storageBucket: 'capypocket.firebasestorage.app',
    iosBundleId: 'com.example.capyproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT66hSkvnkb97ANwErT0HUUE-tW1jUmac',
    appId: '1:1040386855221:web:5a7a3cf27f75d358e93c7c',
    messagingSenderId: '1040386855221',
    projectId: 'capypocket',
    authDomain: 'capypocket.firebaseapp.com',
    storageBucket: 'capypocket.firebasestorage.app',
    measurementId: 'G-7HE3F98PMG',
  );
}
